### ISSUE TITLE
코드 구현 전 논의

### ISSUE THREAD

**Issue by SeungheeJeongHL** [morehey/2023OSS_TeamProject#5]
그 저희 팀프로젝트 코드 구현하는 과정에 대한 의견 인데요, 
일단 main 함수가 있고 어떤 함수를 사용할지가 대략적으로라도 틀이 짜여져 있어야지 저희가 코드를 구현하는게 의미있게 흘러갈 것 같아요!
그래서, 제가 최대한 빨리 내일 아니면 정말 늦으면 모레까지 main함수와 짜야할 함수의 틀 (parameter, return 값등)을 정리해서 올릴게요.
그러면 그 때부터 각자 맡을 함수를 정해서 구현하는 거 어떠시나요?

**Comment by juno5626** [comment]
그러면 너무 감사하죠..ㅎㅎ  
그리고 혹시라도 parameter, return 값을 정리할 때 막히는 부분있으면 언제든지 공유해 주세요!

**Comment by SeungheeJeongHL** [comment]
코드 다 올렸습니다! 
기존에 말했다시피
정환 : Mode 1
현준 : Mode 2 + 메뉴판 File 불러오기
승희 : Mode 3 
코드 구현해요!!

**Comment by SeungheeJeongHL** [comment]
코드에도 적었고, pr에도 적었긴 하지만 혹시나 못 보실까봐 한번 더 올릴게요

드리고 싶은 말은!
이전 교수님께서 CRUD 구현하셨을 때 한 내용을 바탕으로 함수와 코드를 만들었고요
제가 사실 어느정도까지 틀을 잡아야할지 모르겠어서
일단 최대한 자세하게 적어놓긴 했습니다.
최대한 충돌을 피하게 하기 위해서 그랬는데,
어떤 분에게는 너무 자율성을 침해한다고 느낄수도 있을 것 같아 조심스럽네요..
한번 코드 읽어보시고, 충돌이 일어나지 않는다 싶으면 얼마든지 마음대로 바꾸셔도 됩니다!
그리고.. 틀린 부분이 있을수도 있습니다..ㅠㅠ
혹시 잘못된 부분은 언제든지 알려주세요!
의견, 질문하셔도 완전 좋습니다:)
